# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mytimelog.ui'
#
# Created: Fri Dec 21 09:42:48 2012
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(9, 9, 256, 192))
        self.treeView.setAllColumnsShowFocus(True)
        self.treeView.setObjectName("treeView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.fileNewAction = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/filenew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileNewAction.setIcon(icon1)
        self.fileNewAction.setObjectName("fileNewAction")
        self.fileOpenAction = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenAction.setIcon(icon2)
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileSaveAction = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSaveAction.setIcon(icon3)
        self.fileSaveAction.setObjectName("fileSaveAction")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName("actionSave_As")
        self.fileQuitAction = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/images/filequit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileQuitAction.setIcon(icon4)
        self.fileQuitAction.setObjectName("fileQuitAction")
        self.editAddAction = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/images/editadd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editAddAction.setIcon(icon5)
        self.editAddAction.setObjectName("editAddAction")
        self.editDeleteAction = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/images/editdelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editDeleteAction.setIcon(icon6)
        self.editDeleteAction.setObjectName("editDeleteAction")
        self.editCutAction = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/images/editcut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCutAction.setIcon(icon7)
        self.editCutAction.setObjectName("editCutAction")
        self.editPasteAction = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/images/editpaste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPasteAction.setIcon(icon8)
        self.editPasteAction.setObjectName("editPasteAction")
        self.fileSaveAsAction = QtGui.QAction(MainWindow)
        self.fileSaveAsAction.setIcon(icon3)
        self.fileSaveAsAction.setObjectName("fileSaveAsAction")
        self.editMoveUpAction = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/images/editup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editMoveUpAction.setIcon(icon9)
        self.editMoveUpAction.setObjectName("editMoveUpAction")
        self.editMoveDownAction = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/images/editdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editMoveDownAction.setIcon(icon10)
        self.editMoveDownAction.setObjectName("editMoveDownAction")
        self.editPromoteAction = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/images/editpromote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPromoteAction.setIcon(icon11)
        self.editPromoteAction.setObjectName("editPromoteAction")
        self.editDemoteAction = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/images/editdemote.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editDemoteAction.setIcon(icon12)
        self.editDemoteAction.setObjectName("editDemoteAction")
        self.editStartOrStopAction = QtGui.QAction(MainWindow)
        self.editStartOrStopAction.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/images/0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editStartOrStopAction.setIcon(icon13)
        self.editStartOrStopAction.setObjectName("editStartOrStopAction")
        self.menuFile.addAction(self.fileNewAction)
        self.menuFile.addAction(self.fileOpenAction)
        self.menuFile.addAction(self.fileSaveAction)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.fileQuitAction)
        self.menuEdit.addAction(self.editAddAction)
        self.menuEdit.addAction(self.editDeleteAction)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.editCutAction)
        self.menuEdit.addAction(self.editPasteAction)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.editMoveUpAction)
        self.menuEdit.addAction(self.editMoveDownAction)
        self.menuEdit.addAction(self.editPromoteAction)
        self.menuEdit.addAction(self.editDemoteAction)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.editStartOrStopAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.fileNewAction)
        self.toolBar.addAction(self.fileOpenAction)
        self.toolBar.addAction(self.fileSaveAction)
        self.toolBar_2.addAction(self.editAddAction)
        self.toolBar_2.addAction(self.editDeleteAction)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.editCutAction)
        self.toolBar_2.addAction(self.editPasteAction)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.editMoveUpAction)
        self.toolBar_2.addAction(self.editMoveDownAction)
        self.toolBar_2.addAction(self.editPromoteAction)
        self.toolBar_2.addAction(self.editDemoteAction)
        self.toolBar_2.addSeparator()
        self.toolBar_2.addAction(self.editStartOrStopAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Timelog - [*]", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setToolTip(QtGui.QApplication.translate("MainWindow", "create a new file", None, QtGui.QApplication.UnicodeUTF8))
        self.fileNewAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setToolTip(QtGui.QApplication.translate("MainWindow", "open a file", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As ...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileQuitAction.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.editAddAction.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.editAddAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.editDeleteAction.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.editDeleteAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setText(QtGui.QApplication.translate("MainWindow", "Past", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAsAction.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.editMoveUpAction.setText(QtGui.QApplication.translate("MainWindow", "Move Up", None, QtGui.QApplication.UnicodeUTF8))
        self.editMoveUpAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Up", None, QtGui.QApplication.UnicodeUTF8))
        self.editMoveDownAction.setText(QtGui.QApplication.translate("MainWindow", "Move Down", None, QtGui.QApplication.UnicodeUTF8))
        self.editMoveDownAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Down", None, QtGui.QApplication.UnicodeUTF8))
        self.editPromoteAction.setText(QtGui.QApplication.translate("MainWindow", "Promote", None, QtGui.QApplication.UnicodeUTF8))
        self.editPromoteAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.editDemoteAction.setText(QtGui.QApplication.translate("MainWindow", "Demote", None, QtGui.QApplication.UnicodeUTF8))
        self.editDemoteAction.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.editStartOrStopAction.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))

import mytimelog_rc
