######################################################################
# Automatically generated by qmake (2.01a) Wed May 8 11:27:08 2013
######################################################################

TEMPLATE = lib
QT       -= gui
DEFINES += BAR_LIBRARY
HEADERS += bar.h
SOURCES += bar.cpp
